# Name of the pipeline
name: MRF-Front-End-Build-Pipeline
appendCommitMessageToRunName: false

# Define the trigger for the pipeline to run when changes occur in azure-pipelines branch
trigger:
- web_mrf

# Use the latest Ubuntu image as the build agent pool
pool:
  vmImage: ubuntu-latest

# Define variables for the source and build directories
variables:
  uiSource: 'web'
  uiBuild: '$(uiSource)/build'

# Define the sequence of steps to execute in the pipeline
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js' # Displayed name for the step

- script: |
    cd $(uiSource) # Change directory to the specified source
    npm install    # Install dependencies
    npm run build  # Build the application
  displayName: 'npm install and build' # Displayed name for the step

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(uiBuild)' # Set the path to publish artifacts
    artifactName: 'drop'         # Define the name for the artifact
    publishLocation: 'Container' # Publish artifacts to the build container
